#### NEVER USED

In [3]:
# def implicit():
#     from google.cloud import storage

#     # If you don't specify credentials when constructing the client, the
#     # client library will look for credentials in the environment.
#     storage_client = storage.Client()

#     # Make an authenticated API request
#     buckets = list(storage_client.list_buckets())
#     print(buckets)

In [4]:
# wget https://github.com/GoogleCloudPlatform/python-docs-samples/raw/master/vision/cloud-client/detect/resources/wakeupcat.jpg

##### INSTALLED

In [5]:
# pip install --upgrade google-cloud-vision

In [6]:
import numpy as np
import pandas as pd

##### google cloud SDK

In [7]:
import io
import os

# Imports the Google Cloud client library
from google.cloud import vision
from google.cloud.vision import types

In [8]:
# Original Instructions advised the following for credentials which did not work:

# GOOGLE_APPLICATION_CREDENTIALS = "./Vision-API/flood-car-classifier-3de49495f20b.json" -- commented out

In [9]:
# Code Reference From: https://github.com/googleapis/google-cloud-python/issues/5349

from google.oauth2 import service_account

credentials = service_account.Credentials. from_service_account_file("./Vision-API/flood-car-classifier-3de49495f20b.json")

In [10]:
def image_labeler(file_list, string__no_flood_OR_flood):
    
    # Create dictionary for image filename & image labels
    image_dict = {}
    
    for file in file_list:
    
        # Instantiates a client
        client = vision.ImageAnnotatorClient(credentials=credentials)

        # The name of the image file to annotate
        file_name = os.path.abspath('./Vision-API/images/' + string__no_flood_OR_flood + '/' + file)

        # Loads the image into memory
        with io.open(file_name, 'rb') as image_file:
            content = image_file.read()

        image = types.Image(content=content)

        # Performs label detection on the image file
        response = client.label_detection(image=image)
        labels = response.label_annotations
        
        # Create list of image labels
        image_list = []
        
        # Loop through each images assigned labels
        for label in labels:
            image_list.append(label.description)
        
        # Add image filename & labels to dictionary
        image_dict[file] = image_list
        
    return image_dict

In [11]:
flood_list = ['BMW_3series_2.jpeg', 'BMW_3series.jpeg', 'BMW_328i_2.jpg', 'BMW_328i.jpg', 'BMW_330i.jpeg', 'BMW_528i.jpeg', 'BMW_X5.jpeg', 'BMW_X6.jpg', 'BMW.jpeg', 'Ferrari_2.jpeg', 'Ferrari_3.jpeg', 'Ferrari.jpg', 'Lamborghini_waldo.jpeg', 'Lamborghini.jpeg', 'Lamborghini.png', 'Maserati_1.jpeg', 'Maserati_Coupe.jpeg', 'Maserati_Levania.jpeg', 'Maserati_Sedan.jpeg', 'Maserati_SUV_1.jpeg', 'Maserati_SUV.jpeg', 'Mercedes_1.jpeg', 'Mercedes_2.jpeg', 'Mercedes_3.jpg', 'Mercedes_4.jpeg', 'Porsche_911_2.jpeg', 'Porsche_911.jpg', 'RollsRoyce_Ph_2.jpg', 'RollsRoyce_Phantom_2.jpeg', 'RollsRoyce_Phantom.jpeg']

In [12]:
no_flood_list = ['BMW_328i.jpg', 'BMW_528i_2.jpg', 'BMW_528i.jpg', 'BMW_X3.png', 'BMW_X5.jpg', 'BMW_X6.jpg', 'Ferrari_2.jpeg', 'Ferrari.jpeg', 'Lamborghini_3.jpg', 'Lamborghini_23.jpg', 'Lamborghini.jpg', 'Maserati_2.jpg', 'Maserati_3.jpeg', 'Maserati_Leavnte.jpg', 'Maserati.jpeg', 'Mercedes_CLA.jpg', 'Mercedes_E_class.jpg', 'Mercedes_Sedan.png', 'Mercedes.png', 'Porsche_911_2.jpg', 'Porsche_911_3.jpg', 'Porsche_911_4.png', 'Porsche_911.jpg', 'RollsRoycePhantom.jpg', 'RollsRoycePhantom2.jpg', 'RollsRoycePhantom3.jpg', 'RollsRoycePhantom4.jpg', 'RollsRoycePhantom5.jpg']

In [218]:
flood_dict = image_labeler(flood_list, 'flood')

In [219]:
no_flood_dict = image_labeler(no_flood_list, 'no_flood')

In [314]:
fl_df = pd.DataFrame(flood_dict.items(), columns=['filename', 'labels'])
fl_df['flood_in_image'] = True
fl_df.filename = 'FL_' + fl_df.filename

no_fl_df = pd.DataFrame(no_flood_dict.items(), columns=['filename', 'labels'])
no_fl_df['flood_in_image'] = False
no_fl_df.filename = 'NO_FL_' + fl_df.filename

no_fl_df
fl_df

noflfl_df = pd.concat([fl_df, no_fl_df], axis=0).reset_index().drop(columns='index')
noflfl_df

,filename,labels,flood_in_image
0,FL_BMW_3series_2.jpeg,"[Water, Waterway, Vehicle, Car, Tree, Flood, N...",True
1,FL_BMW_3series.jpeg,"[Land vehicle, Vehicle, Car, Road, Driving, Sp...",True
2,FL_BMW_328i_2.jpg,"[Vehicle, Car, Night, Automotive lighting, Flo...",True
3,FL_BMW_328i.jpg,"[Vehicle, Car, Rain, Mode of transport, Flood,...",True
4,FL_BMW_330i.jpeg,"[Motor vehicle, Windshield, Rear-view mirror, ...",True
5,FL_BMW_528i.jpeg,"[Vehicle, Car, Flood, Event, River, Watercours...",True
6,FL_BMW_X5.jpeg,"[Bridge, Waterway, Vehicle, Water, Car, Water ...",True
7,FL_BMW_X6.jpg,"[Land vehicle, Vehicle, Car, Bmw, Mode of tran...",True
8,FL_BMW.jpeg,"[Luxury vehicle, Vehicle, Car, Personal luxury...",True
9,FL_Ferrari_2.jpeg,"[Land vehicle, Vehicle, Car, Supercar, Sports ...",True
10,FL_Ferrari_3.jpeg,"[Land vehicle, Vehicle, Car, Sports car, Luxur...",True
11,FL_Ferrari.jpg,"[Land vehicle, Vehicle, Car, Automotive design...",True
12,FL_Lamborghini_waldo.jpeg,"[Vehicle, Car, Flood, Traffic, Transport, Mode...",True
13,FL_Lamborghini.jpeg,"[Vehicle, Car, Supercar, Yellow, Sports car, A...",True
14,FL_Lamborghini.png,"[Land vehicle, Vehicle, Car, Motor vehicle, Su...",True
15,FL_Maserati_1.jpeg,"[Land vehicle, Vehicle, Car, Coupé, Performanc...",True
16,FL_Maserati_Coupe.jpeg,"[Vehicle, Transport, Mode of transport, Car, C...",True
17,FL_Maserati_Levania.jpeg,"[Vehicle, Car, Waterway, River, Off-roading, M...",True
18,FL_Maserati_Sedan.jpeg,"[Land vehicle, Vehicle, Car, Maserati granturi...",True
19,FL_Maserati_SUV_1.jpeg,"[Vehicle, Car, Flood, River, Mode of transport...",True
20,FL_Maserati_SUV.jpeg,"[Watercourse, Geological phenomenon, Waterway,...",True
21,FL_Mercedes_1.jpeg,"[Land vehicle, Vehicle, Car, Mid-size car, Tre...",True
22,FL_Mercedes_2.jpeg,"[Motor vehicle, Vehicle, Crash, Car, Flood, Mo...",True
23,FL_Mercedes_3.jpg,"[Vehicle, Car, Automotive design, Mid-size car...",True
24,FL_Mercedes_4.jpeg,"[Rain, Neighbourhood, Flood, Street, Mode of t...",True
25,FL_Porsche_911_2.jpeg,"[Vehicle, Car, Motor vehicle, Luxury vehicle, ...",True
26,FL_Porsche_911.jpg,"[Land vehicle, Vehicle, Car, Supercar, Mode of...",True
27,FL_RollsRoyce_Ph_2.jpg,"[Land vehicle, Vehicle, Car, Luxury vehicle, Y...",True
28,FL_RollsRoyce_Phantom_2.jpeg,"[Land vehicle, Vehicle, Luxury vehicle, Car, R...",True
29,FL_RollsRoyce_Phantom.jpeg,"[Land vehicle, Vehicle, Car, Luxury vehicle, R...",True
30,NO_FL_FL_BMW_3series_2.jpeg,"[Land vehicle, Vehicle, Car, Motor vehicle, Pe...",False
31,NO_FL_FL_BMW_3series.jpeg,"[Land vehicle, Vehicle, Car, Alloy wheel, Luxu...",False
32,NO_FL_FL_BMW_328i_2.jpg,"[Land vehicle, Vehicle, Car, Motor vehicle, Ex...",False
33,NO_FL_FL_BMW_328i.jpg,"[Land vehicle, Vehicle, Car, Motor vehicle, Bm...",False
34,NO_FL_FL_BMW_330i.jpeg,"[Land vehicle, Vehicle, Car, Motor vehicle, Bm...",False
35,NO_FL_FL_BMW_528i.jpeg,"[Land vehicle, Vehicle, Car, Motor vehicle, Au...",False
36,NO_FL_FL_BMW_X5.jpeg,"[Land vehicle, Vehicle, Car, Supercar, Sports ...",False
37,NO_FL_FL_BMW_X6.jpg,"[Land vehicle, Vehicle, Car, Supercar, Sports ...",False
38,NO_FL_FL_BMW.jpeg,"[Land vehicle, Vehicle, Car, Supercar, Automot...",False
39,NO_FL_FL_Ferrari_2.jpeg,"[Land vehicle, Vehicle, Car, Supercar, Sports ...",False
40,NO_FL_FL_Ferrari_3.jpeg,"[Land vehicle, Vehicle, Car, Supercar, Sports ...",False
41,NO_FL_FL_Ferrari.jpg,"[Land vehicle, Vehicle, Luxury vehicle, Car, M...",False
42,NO_FL_FL_Lamborghini_waldo.jpeg,"[Land vehicle, Vehicle, Car, Luxury vehicle, M...",False
43,NO_FL_FL_Lamborghini.jpeg,"[Land vehicle, Vehicle, Car, Motor vehicle, Au...",False
44,NO_FL_FL_Lamborghini.png,"[Land vehicle, Vehicle, Car, Sports car, Perfo...",False
45,NO_FL_FL_Maserati_1.jpeg,"[Land vehicle, Vehicle, Car, Automotive design...",False
46,NO_FL_FL_Maserati_Coupe.jpeg,"[Land vehicle, Vehicle, Car, Personal luxury c...",False
47,NO_FL_FL_Maserati_Levania.jpeg,"[Land vehicle, Vehicle, Car, Luxury vehicle, P...",False
48,NO_FL_FL_Maserati_Sedan.jpeg,"[Land vehicle, Vehicle, Car, Automotive design...",False
49,NO_FL_FL_Maserati_SUV_1.jpeg,"[Land vehicle, Vehicle, Car, Supercar, Perform...",False
50,NO_FL_FL_Maserati_SUV.jpeg,"[Land vehicle, Vehicle, Car, Automotive design...",False
51,NO_FL_FL_Mercedes_1.jpeg,"[Land vehicle, Vehicle, Car, Yellow, Supercar,...",False
52,NO_FL_FL_Mercedes_2.jpeg,"[Land vehicle, Vehicle, Car, Automotive design...",False
53,NO_FL_FL_Mercedes_3.jpg,"[Land vehicle, Vehicle, Luxury vehicle, Car, R...",False
54,NO_FL_FL_Mercedes_4.jpeg,"[Land vehicle, Vehicle, Luxury vehicle, Car, R...",False
55,NO_FL_FL_Porsche_911_2.jpeg,"[Land vehicle, Vehicle, Luxury vehicle, Car, R...",False
56,NO_FL_FL_Porsche_911.jpg,"[Land vehicle, Vehicle, Luxury vehicle, Car, R...",False
57,NO_FL_FL_RollsRoyce_Ph_2.jpg,"[Land vehicle, Vehicle, Luxury vehicle, Car, R...",False

In [253]:
flood_df = pd.DataFrame(
    [(k, v) for (k, L) in flood_dict.items() for v in L], 
    columns=['image_file_name', 'labels']
)
flood_df['flood_in_image'] = 'yes'

flood_df['image_file_name'] = flood_df['flood_in_image'] + '_' + flood_df['image_file_name']
flood_df.head()

          image_file_name    labels flood_in_image
0  yes_BMW_3series_2.jpeg     Water            yes
1  yes_BMW_3series_2.jpeg  Waterway            yes
2  yes_BMW_3series_2.jpeg   Vehicle            yes
3  yes_BMW_3series_2.jpeg       Car            yes
4  yes_BMW_3series_2.jpeg      Tree            yes

In [254]:
no_flood_df = pd.DataFrame(
    [(k, v) for (k, L) in no_flood_dict.items() for v in L], 
    columns=['image_file_name', 'labels']
)
no_flood_df['flood_in_image'] = 'no'

no_flood_df['image_file_name'] = no_flood_df['flood_in_image'] + '_' + no_flood_df['image_file_name']
no_flood_df.head()

   image_file_name               labels flood_in_image
0  no_BMW_328i.jpg         Land vehicle             no
1  no_BMW_328i.jpg              Vehicle             no
2  no_BMW_328i.jpg                  Car             no
3  no_BMW_328i.jpg        Motor vehicle             no
4  no_BMW_328i.jpg  Personal luxury car             no

In [255]:
sample_df = pd.concat([flood_df, no_flood_df])
sample_df

               image_file_name             labels flood_in_image
0       yes_BMW_3series_2.jpeg              Water            yes
1       yes_BMW_3series_2.jpeg           Waterway            yes
2       yes_BMW_3series_2.jpeg            Vehicle            yes
3       yes_BMW_3series_2.jpeg                Car            yes
4       yes_BMW_3series_2.jpeg               Tree            yes
..                         ...                ...            ...
275  no_RollsRoycePhantom5.jpg        Rolls-royce             no
276  no_RollsRoycePhantom5.jpg      Motor vehicle             no
277  no_RollsRoycePhantom5.jpg              Sedan             no
278  no_RollsRoycePhantom5.jpg  Rolls-royce ghost             no
279  no_RollsRoycePhantom5.jpg      Full-size car             no

[573 rows x 3 columns]

In [256]:
sample_df.groupby('labels')[['image_file_name']].count().sort_values(by='image_file_name', ascending=False)

                   image_file_name
labels
Vehicle                         58
Car                             56
Land vehicle                    41
Luxury vehicle                  33
Automotive design               31
...                            ...
Crossover suv                    1
Porsche 911                      1
Precipitation                    1
Rear-view mirror                 1
Pickup truck                     1

[103 rows x 1 columns]

In [257]:
sorted(sample_df.labels.unique())

# Words that may suggest flooding pulled from above and manually added to list
flood_key_words = ['Geological phenomenon', 'Low water crossing', 'Mud', 'Precipitation', 'Rain', 'Rescue', 'River', 'Stream', 'Water', 'Water resources', 'Watercourse', 'Waterway',]

In [258]:
modeling_df = sample_df
modeling_df

               image_file_name             labels flood_in_image
0       yes_BMW_3series_2.jpeg              Water            yes
1       yes_BMW_3series_2.jpeg           Waterway            yes
2       yes_BMW_3series_2.jpeg            Vehicle            yes
3       yes_BMW_3series_2.jpeg                Car            yes
4       yes_BMW_3series_2.jpeg               Tree            yes
..                         ...                ...            ...
275  no_RollsRoycePhantom5.jpg        Rolls-royce             no
276  no_RollsRoycePhantom5.jpg      Motor vehicle             no
277  no_RollsRoycePhantom5.jpg              Sedan             no
278  no_RollsRoycePhantom5.jpg  Rolls-royce ghost             no
279  no_RollsRoycePhantom5.jpg      Full-size car             no

[573 rows x 3 columns]

In [259]:
modeling_df['flood_in_image'] = [1 if i == 'yes' else 0 for i in modeling_df['flood_in_image']]
modeling_df

               image_file_name             labels  flood_in_image
0       yes_BMW_3series_2.jpeg              Water               1
1       yes_BMW_3series_2.jpeg           Waterway               1
2       yes_BMW_3series_2.jpeg            Vehicle               1
3       yes_BMW_3series_2.jpeg                Car               1
4       yes_BMW_3series_2.jpeg               Tree               1
..                         ...                ...             ...
275  no_RollsRoycePhantom5.jpg        Rolls-royce               0
276  no_RollsRoycePhantom5.jpg      Motor vehicle               0
277  no_RollsRoycePhantom5.jpg              Sedan               0
278  no_RollsRoycePhantom5.jpg  Rolls-royce ghost               0
279  no_RollsRoycePhantom5.jpg      Full-size car               0

[573 rows x 3 columns]

In [260]:
modeling_df = pd.get_dummies(modeling_df, columns=['labels'], drop_first=True)
modeling_df

,image_file_name,flood_in_image,labels_Auto part,labels_Automotive design,labels_Automotive lighting,labels_Automotive mirror,labels_Automotive tire,labels_Automotive wheel system,labels_Automotive window part,labels_Bank,...,labels_Vehicle,labels_Water,labels_Water resources,labels_Watercourse,labels_Waterway,labels_Wheel,labels_White,labels_Windscreen wiper,labels_Windshield,labels_Yellow
0,yes_BMW_3series_2.jpeg,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,yes_BMW_3series_2.jpeg,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,yes_BMW_3series_2.jpeg,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,yes_BMW_3series_2.jpeg,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,yes_BMW_3series_2.jpeg,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,no_RollsRoycePhantom5.jpg,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
276,no_RollsRoycePhantom5.jpg,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
277,no_RollsRoycePhantom5.jpg,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
278,no_RollsRoycePhantom5.jpg,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
279,no_RollsRoycePhantom5.jpg,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [261]:
modeling_df = modeling_df.groupby('image_file_name').sum()
modeling_df.head()

,flood_in_image,labels_Auto part,labels_Automotive design,labels_Automotive lighting,labels_Automotive mirror,labels_Automotive tire,labels_Automotive wheel system,labels_Automotive window part,labels_Bank,labels_Blue,...,labels_Vehicle,labels_Water,labels_Water resources,labels_Watercourse,labels_Waterway,labels_Wheel,labels_White,labels_Windscreen wiper,labels_Windshield,labels_Yellow
image_file_name,,,,,,,,,,,,,,,,,,,,,
no_BMW_328i.jpg,0,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
no_BMW_528i.jpg,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
no_BMW_528i_2.jpg,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
no_BMW_X3.png,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
no_BMW_X5.jpg,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [262]:
modeling_df['flood_in_image'] = [1 if i > 0 else 0 for i in modeling_df['flood_in_image']]

In [263]:
modeling_df.shape

(58, 103)

In [269]:
modeling_df.flood_in_image.value_counts()

1    30
0    28
Name: flood_in_image, dtype: int64

In [270]:
len(flood_dict.keys())

30

In [271]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [273]:
X = modeling_df.drop(columns=['flood_in_image'])
y = modeling_df.flood_in_image

In [274]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=2020)

In [275]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [281]:
print(f'Training Score: {lr.score(X_train, y_train)}')
print(f'Testing Score: {lr.score(X_test, y_test)}')

Training Score: 1.0
Testing Score: 0.0016180925630945309

0.0016180925630945309

# COLOR / PROPERTIES detector

In [291]:
def detect_properties(path):
    """Detects image properties in the file."""
    from google.cloud import vision
    import io
    client = vision.ImageAnnotatorClient(credentials=credentials)

    with io.open(path, 'rb') as image_file:
        content = image_file.read()

    image = vision.types.Image(content=content)

    response = client.image_properties(image=image)
    props = response.image_properties_annotation
    print('Properties:')

    for color in props.dominant_colors.colors:
        print('fraction: {}'.format(color.pixel_fraction))
        print('\tr: {}'.format(color.color.red))
        print('\tg: {}'.format(color.color.green))
        print('\tb: {}'.format(color.color.blue))
        print('\ta: {}'.format(color.color.alpha))

    if response.error.message:
        raise Exception(
            '{}\nFor more info on error messages, check: '
            'https://cloud.google.com/apis/design/errors'.format(
                response.error.message))

In [289]:
detect_properties('./Vision-API/images/flood/BMW_528i.jpeg')

Properties:
fraction: 0.17080000042915344
	r: 155.0
	g: 155.0
	b: 156.0
	a:
fraction: 0.1982666701078415
	r: 24.0
	g: 28.0
	b: 22.0
	a:
fraction: 0.012333333492279053
	r: 91.0
	g: 84.0
	b: 25.0
	a:
fraction: 0.20900000631809235
	r: 129.0
	g: 125.0
	b: 119.0
	a:
fraction: 0.01119999960064888
	r: 179.0
	g: 180.0
	b: 187.0
	a:
fraction: 0.004066666588187218
	r: 140.0
	g: 166.0
	b: 195.0
	a:
fraction: 0.056333333253860474
	r: 123.0
	g: 115.0
	b: 97.0
	a:
fraction: 0.0019333333475515246
	r: 158.0
	g: 185.0
	b: 211.0
	a:
fraction: 0.06406666338443756
	r: 46.0
	g: 49.0
	b: 46.0
	a:
fraction: 0.04586666822433472
	r: 50.0
	g: 52.0
	b: 25.0
	a:

# LOGO detector

In [286]:
def detect_logos(path):
    """Detects logos in the file."""
    from google.cloud import vision
    import io
    client = vision.ImageAnnotatorClient(credentials=credentials)

    with io.open(path, 'rb') as image_file:
        content = image_file.read()

    image = vision.types.Image(content=content)

    response = client.logo_detection(image=image)
    logos = response.logo_annotations
    print('Logos:')

    for logo in logos:
        print(logo.description)

    if response.error.message:
        raise Exception(
            '{}\nFor more info on error messages, check: '
            'https://cloud.google.com/apis/design/errors'.format(
                response.error.message))

In [288]:
detect_logos('./Vision-API/images/flood/BMW_528i.jpeg')

Logos:

# LABEL detector

In [290]:
def detect_labels(path):
    """Detects labels in the file."""
    from google.cloud import vision
    import io
    client = vision.ImageAnnotatorClient(credentials=credentials)

    with io.open(path, 'rb') as image_file:
        content = image_file.read()

    image = vision.types.Image(content=content)

    response = client.label_detection(image=image)
    labels = response.label_annotations
    print('Labels:')

    for label in labels:
        print(label.description)

    if response.error.message:
        raise Exception(
            '{}\nFor more info on error messages, check: '
            'https://cloud.google.com/apis/design/errors'.format(
                response.error.message))

# MULTIPLE OBJECT DETECT

In [13]:
def localize_objects(path):
    """Localize objects in the local image.

    Args:
    path: The path to the local file.
    """
    from google.cloud import vision
    client = vision.ImageAnnotatorClient(credentials=credentials)

    with open(path, 'rb') as image_file:
        content = image_file.read()
    image = vision.types.Image(content=content)

    objects = client.object_localization(
        image=image).localized_object_annotations

    print('Number of objects found: {}'.format(len(objects)))
    for object_ in objects:
        print('\n{} (confidence: {})'.format(object_.name, object_.score))
        print('Normalized bounding polygon vertices: ')
        for vertex in object_.bounding_poly.normalized_vertices:
            print(' - ({}, {})'.format(vertex.x, vertex.y))

In [16]:
localize_objects('./Vision-API/images/flood/BMW_328i_2.jpg')

Number of objects found: 1

Car (confidence: 0.7919248938560486)
Normalized bounding polygon vertices:
 - (0.4326073229312897, 0.38457465171813965)
 - (0.6789053082466125, 0.38457465171813965)
 - (0.6789053082466125, 0.5897743701934814)
 - (0.4326073229312897, 0.5897743701934814)

In [17]:
localize_objects('./Vision-API/images/flood/BMW_3series_2.jpeg')

Number of objects found: 3

Car (confidence: 0.8822342753410339)
Normalized bounding polygon vertices:
 - (0.47160959243774414, 0.24258814752101898)
 - (0.709888756275177, 0.24258814752101898)
 - (0.709888756275177, 0.35104337334632874)
 - (0.47160959243774414, 0.35104337334632874)

Van (confidence: 0.5826497077941895)
Normalized bounding polygon vertices:
 - (0.04615221545100212, 0.1918601393699646)
 - (0.27540069818496704, 0.1918601393699646)
 - (0.27540069818496704, 0.28334781527519226)
 - (0.04615221545100212, 0.28334781527519226)

Car (confidence: 0.5469547510147095)
Normalized bounding polygon vertices:
 - (0.6718935370445251, 0.22335933148860931)
 - (0.8195386528968811, 0.22335933148860931)
 - (0.8195386528968811, 0.30399176478385925)
 - (0.6718935370445251, 0.30399176478385925)

In [20]:
localize_objects('./Vision-API/images/flood/BMW_3series.jpeg')

Number of objects found: 3

Person (confidence: 0.9199126958847046)
Normalized bounding polygon vertices:
 - (0.676562488079071, 0.33795562386512756)
 - (0.7589500546455383, 0.33795562386512756)
 - (0.7589500546455383, 0.5803750157356262)
 - (0.676562488079071, 0.5803750157356262)

Car (confidence: 0.8917667269706726)
Normalized bounding polygon vertices:
 - (0.3371438682079315, 0.340326189994812)
 - (0.6858775019645691, 0.340326189994812)
 - (0.6858775019645691, 0.596850574016571)
 - (0.3371438682079315, 0.596850574016571)

Person (confidence: 0.8680146336555481)
Normalized bounding polygon vertices:
 - (0.4031130373477936, 0.35140159726142883)
 - (0.46659156680107117, 0.35140159726142883)
 - (0.46659156680107117, 0.5365269780158997)
 - (0.4031130373477936, 0.5365269780158997)